enable: etcd
etcd:
  rootDirectory: openim
  # [标准化部署] 原由 docker-compose IMENV_DISCOVERY_ETCD_ADDRESS 注入，现固化到配置文件
  address: [etcd:2379]
  ## Attention: If you set auth in etcd
  ## you must also update the username and password in Chat project.
  # [标准化部署] 原由 IMENV_DISCOVERY_ETCD_USERNAME / IMENV_DISCOVERY_ETCD_PASSWORD 注入
  username:
  password:

kubernetes:
  namespace: default

rpcService:
  user: user-rpc-service
  friend: friend-rpc-service
  msg: msg-rpc-service
  push: push-rpc-service
  messageGateway: messagegateway-rpc-service
  group: group-rpc-service
  auth: auth-rpc-service
  conversation: conversation-rpc-service
  third: third-rpc-service
