# [标准化部署] 原由 docker-compose IMENV_REDIS_ADDRESS 注入 (${REDIS_ADDRESS}=redis:6379)
address: [redis:6379]
username:
password: openIM123
# redis Mode, including "standalone","cluster","sentinel"
redisMode: "standalone"
db: 0
maxRetry: 10
poolSize: 100
# Sentinel configuration (only used when redisMode is "sentinel")
sentinelMode:
  masterName: "redis-master"
  sentinelsAddrs: ["127.0.0.1:26379", "127.0.0.1:26380", "127.0.0.1:26381"]
  routeByLatency: true
  routeRandomly: true
